### ISSUE TITLE
Make it possible to limit the range of possible image sizes

### ISSUE THREAD

**Issue by zaiev** [shifr/imgwizard#1]
Subj. Your /tmp will die if I want to make 100000 size variants of the site's images. Something like:

```
RESIZE_PARAMS_RANGE = 100x50, 420x, 800x
```

And disable any processing if my resize param is out of this range. Should be great.

**Comment by shifr** [comment]
Done! 
Don't forget to update imgwizard `go get -u github.com/shifr/imgwizard`

Now you can run imgwizard with command-line params
Example: `imgwizard -s 100x50,420x,800x`

If you'll try to fetch image with size that not listed in allowed sizes, you'll get 404 error without any processing
