### ISSUE TITLE
Single axis scaling works inconsistently across axes

### ISSUE THREAD

**Issue by zrxq** [shifr/imgwizard#15]
e.g. 
- https://m3.cdnmk.net/imgw/loc/100x/uploads/product_image/2016/07/005/ae021b15-858b-4b66-af0c-b23528dc414e_67605c9b13ae4fe34b3bf08685405c3a_1x1.jpg (locked width, free height) scales to fit, as expected, ie. returns a 100x139 image.
- https://m3.cdnmk.net/imgw/loc/x100/uploads/product_image/2016/07/005/ae021b15-858b-4b66-af0c-b23528dc414e_67605c9b13ae4fe34b3bf08685405c3a_1x1.jpg (locked height, free width) returns a 100x100 image, scaled to fill. That kinda defeats the purpose, if I'd wanted both of the axes locked, I'd request exactly that in the first place.

**Comment by shifr** [comment]
Hi. Yes you're right. This commit closes it https://github.com/shifr/vips/commit/efb047973e07e5a454efe5fc94722858de6d2ee9. 
Thank you for your contribution
